# Generated by Django 3.2.17 on 2023-05-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesVerbal',
            fields=[
                ('NumProcesV', models.IntegerField(primary_key=True, serialize=False)),
                ('resum', models.CharField(max_length=1024)),
            ],
        ),
    ]
