# Generated by Django 3.2.17 on 2023-05-14 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_activitesdept'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActDeptVerbal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numAct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.activitesdept')),
                ('numProcesV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.procesverbal')),
            ],
        ),
    ]
