# Generated by Django 3.2.17 on 2023-05-14 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_actdeptverbal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=1024)),
                ('numActDept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.activitesdept')),
                ('numEmploye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employe')),
            ],
        ),
    ]
