# Generated by Django 3.2.17 on 2023-05-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_departement_numagendadept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='numAgendaDept',
            field=models.IntegerField(),
        ),
    ]
