# Generated by Django 3.2.17 on 2023-05-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_departement_numagendadept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='numAgendaDept',
        ),
    ]
